### ISSUE TITLE
NpcLib is not initialized

### ISSUE THREAD

**Issue by Farmeurimmo** [dandan2611/NpcLib#9]
Bonjour,

Je suis en train d'essayer d'utiliser la librairie. Je récupère cette erreur au démarrage de mon plugin.

```
java.lang.IllegalStateException: NpcLib is not initialized
        at Skyblock.jar/fr.farmeurimmo.npclib.api.NpcLib.api(NpcLib.java:23) ~[Skyblock.jar:?]
        at Skyblock.jar/fr.farmeurimmo.skyblock.purpur.dependencies.npcs.NPCManager.<init>(NPCManager.java:22) ~[Skyblock.jar:?]
        at Skyblock.jar/fr.farmeurimmo.skyblock.purpur.Skyblock.onEnable(Skyblock.java:171) ~[Skyblock.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:211) ~[slimeworldmanager-1.21.1.jar:1.21.1-16392-ba950ec]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[slimeworldmanager-1.21.1.jar:1.21.1-16392-ba950ec]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:642) ~[slimeworldmanager-1.21.1.jar:1.21.1-16392-ba950ec]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:591) ~[slimeworldmanager-1.21.1.jar:1.21.1-16392-ba950ec]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:768) ~[slimeworldmanager-1.21.1.jar:1.21.1-16392-ba950ec]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:515) ~[slimeworldmanager-1.21.1.jar:1.21.1-16392-ba950ec]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) ~[slimeworldmanager-1.21.1.jar:1.21.1-16392-ba950ec]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1229) ~[slimeworldmanager-1.21.1.jar:1.21.1-16392-ba950ec]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[slimeworldmanager-1.21.1.jar:1.21.1-16392-ba950ec]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

Le plugin est bien installé sur le serveur avec la version 2.8.1.

Dans mon plugin.yml, je dépends du plugin NpcLib comme demandé dans la doc:
![image](https://github.com/user-attachments/assets/884b2810-d7e0-4dd3-b5db-d3d169e12c27)

Voici un extrait en image de ma console au démarrage:
![image](https://github.com/user-attachments/assets/cfbd3187-575b-4d91-bd25-08a6ce1e3ef2)

J'ai dans ma configuration gradle ceci:
![image](https://github.com/user-attachments/assets/52d56ce7-06f2-4086-92ae-969b6e36884a)
![image](https://github.com/user-attachments/assets/24590c15-4fe3-4bc6-8165-22c2cc3adcac)

Mon code:
![image](https://github.com/user-attachments/assets/8c67d162-bf66-4a97-8f28-3550bed2cd29)

Ma version serveur:

![image](https://github.com/user-attachments/assets/2af7bd93-efe5-466e-b786-3e90f3b66879)
`This server is running AdvancedSlimePaper version 1.21.1-16392-paper_upstream@ba950ec (2024-10-21T16:24:13Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)`

La liste des plugins sur mon serveur:
![image](https://github.com/user-attachments/assets/e4b8aac7-dfda-4263-8bd3-43457d5cebb2)

**Comment by dandan2611** [comment]
Hello :)

Il faut bien inclure la dépendance en utilisant ` compileOnly` et non la shade, comme ici, avec `implementation` dans la déclaration Gradle.

**Comment by Farmeurimmo** [comment]
> Hello :)
> 
> Il faut bien inclure la dépendance en utilisant ` compileOnly` et non la shade, comme ici, avec `implementation` dans la déclaration Gradle.

Effectivement en compileOnly c'est good, merci.
